### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by kpgarrod** [gocardless/es6-angularjs#2]
How do you handle annotations? I see that assetgraph-builder has a dependency on ngmin, which is deprecated. There is [an open issue](https://github.com/assetgraph/assetgraph-builder/issues/121) to upgrade to ng-annotate, but apparently no skills in the project to do so. I like the look of assetgraph but that would be an issue. How do you deal with it?

**Comment by jackfranklin** [comment]
We don't actually use `ngmin` at all - assetgraph-builder may run it, but it won't do anything to our code.

We use the more verbose syntax for defining Angular components:

``` js
export var currentUserModule = angular.module('currentUserModule', [
]).factory('CurrentUser', [
  '$q',
  function CurrentUser($q) {
    ...
  }
])
```

By using this we don't need to use ngmin / ng-annotate.

If you have any further Qs please ask away :)
