### ISSUE TITLE
font-awesome

### ISSUE THREAD

**Issue by jaulz** [gocardless/es6-angularjs#4]
How do you use font-awesome? Though you have installed it as a component I cannot see any usage. Does the font file need to be copied somewhere?

Thanks! :)

**Comment by feelepxyz** [comment]
Oh we currently don't use it. Where is it referenced?

**Comment by jaulz** [comment]
Sorry, it seems I installed it sometime at night and forgot about it. I thought it was part of the project as well O:-) 

I just referenced to the CDN now in my index.html... seems to work for the time being but any idea how you would solve that if font awesome was local?

**Comment by feelepxyz** [comment]
Yeah so you should be able to reference any local file from client/ in index.html and it should then get bundled in prod.
