### ISSUE TITLE
Issue Running npm install

### ISSUE THREAD

**Issue by ms-denver** [gocardless/es6-angularjs#7]
I had to install python to run the install script.  

When I run it now I get the following error:

![image](https://cloud.githubusercontent.com/assets/10904786/6604886/76c5c98c-c7f1-11e4-8a41-94c39c7e3d3a.png)

16252 error Windows_NT 6.3.9600
16253 error argv "C:\Users\mschr_000\.nvmw\latest\\node.exe" "C:\Users\mschr_000\.nvmw\latest\node_modules\npm\bin\npm-cli.js" "install"
16254 error node v0.12.0
16255 error npm  v2.5.1
16256 error code ELIFECYCLE
16257 error contextify@0.1.9 install: `node-gyp rebuild`
16257 error Exit status 7
16258 error Failed at the contextify@0.1.9 install script 'node-gyp rebuild'.
16258 error This is most likely a problem with the contextify package,
16258 error not with npm itself.
16258 error Tell the author that this fails on your system:
16258 error     node-gyp rebuild
16258 error You can get their info via:
16258 error     npm owner ls contextify
16258 error There is likely additional logging output above.

**Comment by feelepxyz** [comment]
Not too familiar with node on windows but believe you also need to install visual studio c++ and the windows sdk: https://github.com/TooTallNate/node-gyp#installation
